env:
  CODECOV_TOKEN="7fc64ad8-b033-4801-bec6-224d6e981af0"
language: java
jdk:
  - openjdk11
addons:
  mariadb: '10.4'

before_script:
  - sudo mysql -e 'create user travis@localhost;'
  - sudo mysql -e 'grant all on *.* to travis@localhost;'
  - sudo mysql -e 'create database buildz;'

script:
  ./mvnw clean clover:setup test clover:aggregate clover:clover -Dspring.profiles.active=travis


after-script:
  - bash <(curl -s https://codecov.io/bash)