spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buildz
    driverClassName: com.mysql.cj.jdbc.Driver
    username: buildz
    password: buildz
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: validate
  flyway:
    enabled: true
