spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buildz
    driverClassName: com.mysql.jdbc.Driver
    username: shippable
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: validate
flyway:
  enabled: true
